spring:
  datasource:
    url: jdbc:mysql://47.104.73.127:3306/daily_news?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Lvmq123456!
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
       connection-test-query: SELECT 1 FROM DUAL
       minimum-idle: 1
       maximum-pool-size: 5
       pool-name: daily_news
       auto-commit: false
  jpa:
    database: mysql
    show-sql: true
  
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
  thymeleaf:
    mode: HTML5
    encodeing: UTF-8
    content-type: text/html
    cache: true # Allow Thymeleaf templates to be reloaded at dev time
    prefix: /WEB-INF/templates/
    suffix: .html
  message:
    basename: /i18n/messages
    cache-seconds: 3600
    encoding: utf-8