spring:
  datasource:
    url: jdbc:mysql://47.104.73.127:3306/daily_news?useUnicode=true&characterEncoding=utf8
    username: root
    password: Lvmq123456!
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
       connection-test-query: SELECT 1 FROM DUAL
       minimum-idle: 1
       maximum-pool-size: 5
       pool-name: daily_news
       auto-commit: false
  jpa:
    database: mysql
    show-sql: true