spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daily_news
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
       connection-test-query: SELECT 1 FROM DUAL
       minimum-idle: 1
       maximum-pool-size: 5
       pool-name: daily_news
       auto-commit: false
  jpa:
    database: mysql
    show-sql: true